-- Ensure document_requests supports the 'received' status
-- This migration normalizes the status check constraint so partners can mark
-- document requests as received without database errors.

BEGIN;

-- Drop any existing status check constraint, whether named or autogenerated
DO $$
DECLARE
  constraint_name TEXT;
BEGIN
  SELECT con.conname INTO constraint_name
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
  WHERE rel.relname = 'document_requests'
    AND nsp.nspname = 'public'
    AND con.contype = 'c'
    AND pg_get_constraintdef(con.oid) LIKE '%status%IN%';

  IF constraint_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.document_requests DROP CONSTRAINT %I', constraint_name);
  END IF;
END $$;

-- Recreate the constraint with the full allowed status set
ALTER TABLE public.document_requests
  ADD CONSTRAINT document_requests_status_check
  CHECK (status IN ('pending', 'submitted', 'approved', 'rejected', 'received'));

COMMIT;
